from Pila import Pila
p = Pila()
print p.Vacia()
p.push(5)
p.push(57)
print p.Vacia()
p.push("Hola")
p.push(5)
p.pop()
p.imprimir()
p.push("Como_estas")
p.push("Perro")
p.pop()
p.push("Si_sale_XD")
p.push("funciona")
p.imprimir()
p.GenerarGrafico()